### ISSUE TITLE
我有一个大胆的想法，Win11能不能切换回Win10

### ISSUE THREAD

**Issue by Meta39** [zbezj/HEU_KMS_Activator#109]
因为硬件原因U盘重装系统也只能重装Win11，要不然就只能用第三方PE系统才能重装，但是不想用第三方PE，怕捆绑软件太多。

**Comment by tanmoumou252** [comment]
找不到北了搁这乱发issue



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月18日(周一) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zbezj/HEU_KMS_Activator] 我有一个大胆的想法，Win11能不能切换回Win10 (Issue #109)




 
因为硬件原因U盘重装系统也只能重装Win11，要不然就只能用第三方PE系统才能重装，但是不想用第三方PE，怕捆绑软件太多。

**Comment by keyang556** [comment]
下載win10 iso然後強制降級，但是需要清除全部資料。

**Comment by Meta39** [comment]
解决了，用[rufus](https://github.com/pbatard/rufus)装成U盘PE安装就完事了。
