### ISSUE TITLE
请求更多静默参数

### ISSUE THREAD

**Issue by BadORANGE1337** [zbezj/HEU_KMS_Activator#123]
添加一键启动本地KMS服务器后激活Windows和Office，按计划每次自动执行一次（因为我们教学机是离线的）拜托了大佬

**Comment by ADM-DENG** [comment]
> 添加一键启动本地KMS服务器后激活Windows和Office，按计划每次自动执行一次（因为我们教学机是离线的）拜托了大佬

只要教学机的系统没有开启或安装零点还原相关的功能，那使用该软件一次即可。
因为该软件离线||激活，一般使用的是kms38；在激活后还会给系统安装一个自动续期的功能（一次激活快到期后，会再次调用自动激活）。其它的就不多讲解了。

**Comment by Bad0RANGE** [comment]
但是现在问题就是我的教学机有冰点还原，使用的Office版本是2019需要关闭冰点手动激活一次

**Comment by ADM-DENG** [comment]
`虽然之前知道有冰点还原这个东西，但是没深入了解过。`
呃 .....，既然知道有冰点还原，那就接下来的步骤就是 去除 [ DeepFreeze](https://www.bingdiancn.com/4983.html) （刚百度的）。依据官方文档，还是推荐第二种方法。但教学机非得存在冰点还原来保护系统的话，那看向 [这里](https://www.423down.com/8687.html) 。还有一种省力的办法，那就是 **找为学校教学机安装冰点还原的工作人员要密码**。👈😂

**Comment by Bad0RANGE** [comment]
我的意思就是我就是管电脑的，但是现在我需要每次开机自动启动kms服务器激活Office，因为180天之后他就会自动脱离激活状态，完了之后我就是想他每次开机启动后用脚本运行静默指令自动启动kms服务器激活office这样就不用老是解开冰点还原重新弄了，您看一下？

**Comment by ADM-DENG** [comment]
😒，最省力气，最高效的办法就是关闭冰点还原进行鸡活，然后再开启冰点还原。你所想要的办法已经被冰点还原扼杀在摇篮里面了。

**Comment by Bad0RANGE** [comment]
呃呃呃，您可能还是没看懂，算了，等更新啰

**Comment by yz1639** [comment]
不是提供了静默参数吗？ 你写个bat甩到自启动目录里 不就好了？
按你说的需求，参数应该是这个: `/kwi`

**Comment by Bad0RANGE** [comment]
> 不是提供了静默参数吗？ 你写个bat甩到自启动目录里 不就好了？
> 
> 按你说的需求，参数应该是这个: `/kwi` 
> 
> 
> 
> 而且我看不是有自动续期功能嘛，你要不先try try？😼

我的意思是_先启动本地的kms服务器_再激活，因为教学机并**没有联网**，就算能使用这个“/kwi”的参数，也会因为无法联网而失效

**Comment by BadORANGE1337** [comment]
了解了，这周把全部事情解决了，幸苦你了
