### ISSUE TITLE
密码在哪里

### ISSUE THREAD

**Issue by liuyong888** [zbezj/HEU_KMS_Activator#27]
哪位大哥告知一下密码？
![image](https://user-images.githubusercontent.com/45752479/155921694-bdd1afa3-b3bd-410e-9b24-12dabfa93ae0.png)

**Comment by JayChen1996** [comment]
https://github.com/zbezj/HEU_KMS_Activator/releases 人家发布页不就有密码。。。你从哪儿下的。。。

**Comment by liuyong888** [comment]
谢谢, 看到了
