### ISSUE TITLE
v25.0.0 閃退

### ISSUE THREAD

**Issue by supercjlee** [zbezj/HEU_KMS_Activator#46]
無法啟用，一執行就閃退！......發現是Windows 安全性的問題！

**Comment by tylvn** [comment]
请问如何解决 Windows 安全性造成的问题？

**Comment by Chenx221** [comment]
如果Microsoft defender误报 拦截heu激活，可以用这个禁用ms defender https://www.sordum.org/9480/defender-control-v2-1/
@tylvn 被Microsoft defender拦截的 好像不会提示“此应用无法在你的电脑上运行”

**Comment by tylvn** [comment]
> 如果 Microsoft defender 误报 拦截 heu 激活，可以用这个禁用 ms defender [sordum.org/9480/defender-control-v2-1](https://www.sordum.org/9480/defender-control-v2-1/) @tylvn 被 Microsoft defender 拦截的 好像不会提示 “此应用无法在你的电脑上运行”

我应该已经禁用了 Microsoft Defender🤔

<img width="430" alt="image" src="https://user-images.githubusercontent.com/95011132/182165681-72f345a1-b674-430c-9f99-707dafddf60e.png">


即使更换了 HEU 的版本，也还是会遇到`此应用无法在你的电脑上运行`的状况。

**Comment by tylvn** [comment]
> 提供一下系统版本信息（Win+R，dxdiag） @tylvn

版本	Windows 11 专业版（64 位）
版本	21H2
操作系统版本	22000.832

**Comment by supercjlee** [comment]
只有一個方法就是將HEU KMS Activator的所在目錄新增到排除項目裡（我的是繁體中文版本），就可以執行了！

允許威脅等設定都無效，只能新增到排除項目內才行！

**Comment by tylvn** [comment]
> 只有一個方法就是將HEU KMS Activator的所在目錄新增到排除項目裡（我的是繁體中文版本），就可以執行了！
> 
> 允許威脅等設定都無效，只能新增到排除項目內才行！

是 `Windows 安全中心 > 病毒和威胁防护 > 排除项`吗？如果是这里的话可能也没用，我之前也添加了排除项，但依旧显示无法运行。

不过我已经通过其它开源工具激活了 Windows，暂时不会再去复现该问题。不太清楚将其添加到排除项应该是否可行的，也许是我之前的操作不太对，如果以后有机会我会再尝试的。
