### ISSUE TITLE
Error: Variable used without being declared.

### ISSUE THREAD

**Issue by clay-f** [zbezj/HEU_KMS_Activator#55]
环境：win11 系统已激活
下载26.2最新版后，点击智能激活会报错

win11 版本版本说明

    版本	Windows 11 专业版
    版本	22H2
    安装日期	‎2022/‎10/‎20
    操作系统版本	22621.755
    体验	Windows Feature Experience Pack 1000.22636.1000.0

激活j截图

![win11激活](https://user-images.githubusercontent.com/16079417/200214191-fc716945-b6b9-435a-8e14-d1e3b22a237f.jpg)

报错截图

![屏幕截图 2022-11-07 094542](https://user-images.githubusercontent.com/16079417/200210043-65f9e299-2d3a-4545-b743-2236fd05fded.jpg)

**Comment by qiutongxue** [comment]
同样的问题

![image](https://user-images.githubusercontent.com/53330358/200239192-e1da7443-029e-4f46-aec9-6c82a6648143.png)

**Comment by zbezj** [comment]
已找到原因，准备修复

**Comment by braid123** [comment]
> 已找到原因，准备修复

![image](https://github.com/zbezj/HEU_KMS_Activator/assets/19856479/bf25dd66-4f8d-418d-bf42-7a8d898f3443)
环境：win11 系统已激活
下载42.0.1最新版后，点击智能激活会报错

win11 版本说明
`
版本	Windows 11 专业版 Insider Preview
版本	22H2
安装日期	‎2024/‎1/‎28
操作系统版本	23620.1000
体验	Windows Feature Experience Pack 1000.23620.1000.0
`
