### ISSUE TITLE
无法更改Windows10到家庭版

### ISSUE THREAD

**Issue by guation** [zbezj/HEU_KMS_Activator#62]
1. 在家庭版中启动HEU点击激活信息备份 选中专业版后点击更改并重启
2. 显示专业版未激活
3. 在专业版中启动HEU未找到家庭版选项 点击还原备份显示家庭版未激活
5. 点击疑难解答显示家庭版已激活
6. 重启后显示企业版未激活

家庭版切换版本之后除了重装不能切回来了吗

**Comment by Github-Luke-Zhang** [comment]
应该是。除非你破解DISM命令。转换系统是通过DISM命令的

**Comment by Huh-DIETHGOD** [comment]
所以这个还能恢复吗
如果直接重装系统呢

**Comment by Github-Luke-Zhang** [comment]
重装当然可以
但专业版不好吗，用家庭版干什么

**Comment by Github-Luke-Zhang** [comment]
数字激活可以直接永久激活
