### ISSUE TITLE
Microsoft365激活版本不正确

### ISSUE THREAD

**Issue by Designer247** [zbezj/HEU_KMS_Activator#70]
在激活Microsoft365时识别为Office2016，Mondo
在其它账号下就会变成office2016，无法使用Microsoft365功能。

**Comment by zbezj** [comment]
Microsoft365不支持KMS激活，转换成Mondo 2016才可以激活。绝大部分365的功能都能用，一些云服务例如OneDrive用不了。

**Comment by zbezj** [comment]
> 在激活Microsoft365时识别为Office2016，Mondo 在其它账号下就会变成office2016，无法使用Microsoft365功能。

Microsoft365不支持KMS激活，转换成Mondo 2016才可以激活。绝大部分365的功能都能用，一些云服务例如OneDrive用不了。

**Comment by quannen** [comment]
> > 在激活Microsoft365时识别为Office2016，Mondo 在其它账号下就会变成office2016，无法使用Microsoft365功能。
> 
> Microsoft365不支持KMS激活，转换成Mondo 2016才可以激活。绝大部分365的功能都能用，一些云服务例如OneDrive用不了。

那为啥转换完之后只能激活180天（我的是office21
