### ISSUE TITLE
专业版数字激活失败，日志提示0xC004C003错误，是怎么回事

### ISSUE THREAD

**Issue by chunyu1984** [zbezj/HEU_KMS_Activator#79]
专业版数字激活失败，日志提示0xC004C003错误，是怎么回事
![image](https://user-images.githubusercontent.com/9999814/218300346-41e209c3-9718-467a-bab5-7a85c587b8ad.png)

**Comment by tanmoumou252** [comment]
用kms38吧，最近我装了四五台，全都激活不了数字权利



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月12日(周日) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zbezj/HEU_KMS_Activator] 专业版数字激活失败，日志提示0xC004C003错误，是怎么回事 (Issue #79)




 
专业版数字激活失败，日志提示0xC004C003错误，是怎么回事

**Comment by chunyu1984** [comment]
> 用kms38吧，最近我装了四五台，全都激活不了数字权利
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月12日(周日) 下午4:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zbezj/HEU_KMS_Activator] 专业版数字激活失败，日志提示0xC004C003错误，是怎么回事 (Issue #79) 专业版数字激活失败，日志提示0xC004C003错误，是怎么回事 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是微软服务器限制了吗？

**Comment by shcocj** [comment]
是不是因为微软服务器的问题

**Comment by chunyu1984** [comment]
最新版本修复了这个问题
