### ISSUE TITLE
天下没有免费的午餐，Windows的激活费用昂贵还是您账户上的存款安全昂贵？

### ISSUE THREAD

**Issue by kinmontw** [zbezj/HEU_KMS_Activator#89]
此破解软件至少包含有以下恶意操作
C://Windows/SECOH-QAD.exe

[参考]
https://wubingdu.cn/secoh-qad-exe/

**Comment by cpf23333** [comment]
> 此破解软件至少包含有以下恶意操作 C://Windows/SECOH-QAD.exe
> 
> [参考] https://wubingdu.cn/secoh-qad-exe/

链接里有描述它有什么危害吗，它真的是病毒吗

**Comment by cpf23333** [comment]
> 兄弟我建议你去学习一下，争取早日毕业
> 
> https://tieba.baidu.com/f?kw=%E5%BC%B1%E6%99%BA

我说的有什么问题，你就在这骂人？傻逼玩意

**Comment by bestdecoy** [comment]
行为描述：	设置特殊文件属性
详情信息：	
C:\Windows\_temp_heu168yyds\7Z.EXE

行为描述：	跨进程写入数据
详情信息：	
TargetProcess = C:\Windows\_temp_heu168yyds\7Z.EXE, WriteAddress = 0x00050000, Size = 0x00000020 TargetPID = 0x00000bd8

TargetProcess = C:\Windows\_temp_heu168yyds\7Z.EXE, WriteAddress = 0x00050020, Size = 0x00000034 TargetPID = 0x00000bd8

TargetProcess = C:\Windows\_temp_heu168yyds\7Z.EXE, WriteAddress = 0x7ffd5238, Size = 0x00000004 TargetPID = 0x00000bd8

TargetProcess = C:\Windows\_temp_heu168yyds\x86\kms.exe, WriteAddress = 0x00050000, Size = 0x00000020 TargetPID = 0x00000c00

TargetProcess = C:\Windows\_temp_heu168yyds\x86\kms.exe, WriteAddress = 0x00050020, Size = 0x00000034 TargetPID = 0x00000c00

TargetProcess = C:\Windows\_temp_heu168yyds\x86\kms.exe, WriteAddress = 0x7ffdf238, Size = 0x00000004 TargetPID = 0x00000c00

行为描述：	设置特殊文件夹属性
详情信息：	
C:\Windows\_temp_heu168yyds

看上去并没有释放SECOH-QAD.exe的证据。
